#!/usr/bin/env bash
# Thiprints fizz buzz or fizzbuzzz

i="1"

while [ $i -lt 101 ]
do
if (( i % 15 == 0)); then
	echo "FizzBuzz"
elif (( i % 5 == 0)); then
	echo "Buzz"
elif (( i % 3 == 0)); then
	echo "Fizz"
else
	echo $i
fi
i=$((i+1))
done
